ТЗ 11.
Khanbikov-Askhat/java-filmorate pull request #8
Opened 2023-11-15 12:58 UTC by Khanbikov-Askhat

2023-11-16 15:10 UTC, YazykovMikhail requested changes

2023-11-16 15:10 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDaoImpl.java
> +        for (Film film : foundedFilm) {
представляешь сколько это запрососв в бд?
а запрос в бд - это тяжеловестная штука и их стараются сокразать. 

вот примерно такой метод стоит сделать в сервисе:
```
@Override
public List<Film> getAll() {
		final List<Film> films = super.getAll();
		genreStorage.load(films);
		return films;
	}
```
где genreStorage.load будет выглядеть так:

```
@Override
	public void load(List<Film> films) {
		String inSql = String.join(",", Collections.nCopies(films.size(), "?"));
		final Map<Long, Film> filmById = films.stream().collect(Collectors.toMap(Film::getId, identity()));
		final String sqlQuery = "select * from GENRES g, FILM_GENRES fg where fg.GENRE_ID = g.GENRE_ID AND fg.FILM_ID in (" + inSql + ")";
		jdbcTemplate.query(sqlQuery, (rs) -> {
			final Film film = filmById.get(rs.getLong("FILM_ID"));
			film.addGenre(makeGenre(rs, 0));
		}, films.stream().map(Film::getId).toArray());
	}
```
identity() - import static java.util.function.UnaryOperator.identity;

static Genre makeGenre(ResultSet rs, int rowNum) throws SQLException {
		return new Genre(
				rs.getLong("genre_id"),
				rs.getString("name"));
	}

2023-11-16 15:10 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Rating.java
> +    private final long id;
не делай финал поля в моделях, на то оно и модели что бы иметь свойтво изменяться

2023-11-16 15:10 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  public class Film {
не делай final поля в моделях, на то оно и модели что бы иметь свойтво изменяться

2023-11-16 15:10 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private final Map<Long, Boolean> friends = new HashMap<>();
вообще это не нужно, для работы с дурзьми есть отжельные энгдпоинты, тут их возвращать не нужно

2023-11-22 09:45 UTC, Khanbikov-Askhat commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/FilmDaoImpl.java
> +        for (Film film : foundedFilm) {
На этом месте я прям встал из-за того что сначала падала 500-я ошибка, потом писал, что у меня ошибка в запросе...Оказалось что я нормально список нигде не объявляю. Снова эта ошибка, которая мне будет снитьсяXD

2023-11-22 10:44 UTC, Khanbikov-Askhat commented on src/main/resources/schema.sql
> +    film_id BIGSERIAL PRIMARY KEY,
Если такое править, получиться так, что и у юзера id и у фильма id, это по большей части сделано было, чтобы отличать их
![image](https://github.com/Khanbikov-Askhat/java-filmorate/assets/128650201/c03e439b-170e-4c7f-9cbc-8844d229fa72)

2023-11-22 12:13 UTC, YazykovMikhail requested changes

2023-11-22 12:13 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/implservice/FilmServiceImpl.java
> +        for (Film film: films) {
что бы избежать такого for, можно в Film сделать вот так:
    private List<Genre> genres = new ArrayList<>();

тогда если поле будет null, оно будет пустым списком.

2023-11-22 12:13 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/implservice/FilmServiceImpl.java
> +            film.get().getFilmLikes().addAll(new HashSet<>(filmDao.getLikesByFilmId(filmId)));
в целом тут это уже не нужно, это было нужно когда мы хранили данные в HashMap
теперь они хранятся в БД. 
И когда мы возвращаем данные на том поле стоит @JsonIgnore так что все равно овзаращть не будет. 
Т.е да, для обратной соместимости? если нам резко будет нужно вернуться к реализации хранения HashMap в этом поле будут хранится лайки, но возвращать их не нужно, когда рабоатет с бд.

2023-11-22 12:13 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/implservice/FilmServiceImpl.java
> +            film.get().getFilmLikes().addAll(new HashSet<>(filmDao.getLikesByFilmId(filmId)));
и поэтому метод  можно сдлеать так:

```
public Film findById(Long filmId) {
        Optional<Film> foundedFilm = getFilmById(filmId);
        Film film = foundedFilm.get();
        load((Collections.singletonList(film)));
        return film;
    }
```
 ну только понятно что метод load переедет в GenreDaoImpl

2023-11-22 12:40 UTC, Khanbikov-Askhat commented on src/main/java/ru/yandex/practicum/filmorate/service/implservice/FilmServiceImpl.java
> +        for (Film film: films) {
Это в теории должно помочь, но он все равно проставляет null без подобных проверок, основная проблема скорее в том, что тесты не проходят, сам по себе нулл не проблема, при добавлении какого-либо жанра, он сменится, но для тестов - не ок.

2023-11-22 13:10 UTC, YazykovMikhail approved these changes

2023-11-27 18:35 UTC, merged